version: '3'

services:
  nextjs-app:
    container_name: nextjs-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - secrets.env
    environment:
      - NODE_ENV=production
